apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-python-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-python-http
  template:
    metadata:
      labels:
        app: ff-python-http
    spec:
      containers:
        - name: ff-python-http
          image: ff-python-http:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ff-python-http-service
spec:
  selector:
    app: ff-python-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
